---
- envvars:
    - MYVAR: "myvalue"
      MYVAR2: "myvalue2"
---
- name: "env test"
  tests:
    - cmd: echo $MYVAR
      retcode: 0
      stdout: "myvalue"
      stderr: ""
    - cmd: echo $MYVAR2
      retcode: 0
      stdout: "myvalue2"
      stderr: ""

- name: "uname -a works"
  tests:
    - cmd: uname -a | wc -l
      retcode: 0
      stdout: "1"
      stderr: ""

- name: "internet connectivity"
  tests:
    - cmd: curl -s ifconfig.me | grep -q ^[0-9]
      retcode: 0
      stdout: ""
      stderr: ""

- name: "systemctl is happy"
  tests:
    - cmd: systemctl | grep failed | wc -l
      retcode: 0
      stdout: "0"
      stderr: ""
    - cmd: systemctl is-system-running
      retcode: 0
      stdout: "running"
      stderr: ""

# ignore values, just run the commands
- name: "just run these commands"
  tests:
    - cmd: "true"
    - cmd: "false"
    - cmd: "true"
    - cmd: "false"
